<?xml version="1.0"?>
<!DOCTYPE service [
<!ELEMENT service (description,ID,Name,Available,OS,CPU,Memory,ScreenSize,Languages,Language,Locations,Location,Fee,Display,link)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT ID (#PCDATA)>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT Available (#PCDATA)>
<!ELEMENT OS (#PCDATA)>
<!ELEMENT CPU (#PCDATA)>
<!ELEMENT Memory (#PCDATA)>
<!ELEMENT ScreenSize (#PCDATA)>
<!ELEMENT Languages (#PCDATA)>
<!ELEMENT Language (#PCDATA)>
<!ELEMENT Locations (#PCDATA)>
<!ELEMENT Location (#PCDATA)>
<!ELEMENT Fee (#PCDATA)>
<!ELEMENT Display (#PCDATA)>
<!ELEMENT link (#PCDATA)>
]>
<service>

	<description>
		<ID>11111</ID>
		<Name>Weather</Name>
		<Available>YES</Available>
		
		<OS>2.0</OS>
		<CPU>0.5</CPU>
		<Memory>0.512</Memory>
		<ScreenSize>800*480</ScreenSize>
		
			<Languages>
			<Language>English</Language>
			</Languages>
			
			<Locations>
			<Location>US</Location>
			</Locations>
			
			<Fee>Free</Fee>
			<Display>Graphic</Display>
			
			<link>http://wsf.cdyne.com/WeatherWS/Weather.asmx?WSDL</link>
			
	</description>

</service>
